(when (or (eq system-type 'windows-nt) (eq system-type 'cygwin))
  (setq bash-completion-prog "C:/cygwin/bin/bash")) ;; this should be the cygwin bash

(defun bash-completion-send (commandline &optional process timeout)
  "Send a command to the bash completion process..."
  ;;(message commandline)
  (let ((process (or process (bash-completion-require-process)))
	(timeout (or timeout bash-completion-process-timeout))
        (commandline "PROMPT_COMMAND='';PS1='MYPROMPT'; echo 'hallo'"))
    (with-current-buffer (process-buffer process)
      (display-buffer-other-frame (current-buffer))
      (erase-buffer)
      (process-send-string process (concat commandline "\n"))
      (message commandline))))
      (while (not (progn (goto-char 1) (search-forward "Q" nil t)))
	(unless (accept-process-output process 10)
	  (error "Timeout while waiting for an answer from bash-completion process")))
      (message "")
      (goto-char (point-max))
      (delete-char -1))))

(defun x-send-some ()
  "Send a command to the bash completion process..."
  (let ((process (or process (bash-completion-require-process)))
	(timeout (or timeout bash-completion-process-timeout)))
    (with-current-buffer (process-buffer process)
      (message commandline)
      (erase-buffer)
      (process-send-string process (concat commandline "\n")))))
      (message "B")
      (while (not (progn (goto-char 1) (search-forward "\v" nil t)))
	(unless (accept-process-output process 3)
	  (error "Timeout while waiting for an answer from bash-completion process")))
      (message "")
      (goto-char (point-max))
      (delete-char -1))))
